### PR TITLE
feat: collect cloud VM metadata

### PR DESCRIPTION
**Pull request by luke-zhu**
This change introduces code that collects VM metadata for GCP, AWS, and Azure. This is part of OB-15064

### CODE REVIEW

**Comment by luke-zhu** [comment]
This doesn't work because fluentbit exec doesn't work on windows.

It is still possible to create a cronjob that forwards the json data to Observe through another endpoint.

**Comment by luke-zhu** [comment]
I got it to work with Register-ScheduledJob

It seems like on GCP, Register-ScheduledJob only works if the user runs the script as an administrator.

**Comment by luke-zhu** [comment]
Here is the data in Observe with the primary key columns extracted

image


image

**Comment by luke-zhu** [comment]
linux PR: https://github.com/observeinc/linux-host-configuration-scripts/pull/29

**Review by yasar-observe — APPROVED** [review]

**Pull request merged**
